spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/h2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: h2db
      password: h2db!
      
helloworld:
  datasource:
    h2db:
      pool-name: H2dbDataSource
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:./data/h2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: h2db
      password: h2db!
      maximum-pool-size: 2
  url:
    patterns:
      - /api/**
      
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  override-with-generic-response: false
  
logging:
  level:
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      sqlonly: OFF
      sqltiming: INFO
      connection: OFF
    root: INFO     # 모든 패키지의 기본 로그 레벨