spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/h2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: h2db
      password: h2db!
      
helloworld:
  datasource:
    h2db:
      pool-name: H2dbDataSource
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:./data/h2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: h2db
      password: h2db!
      maximum-pool-size: 2